FROM node:slim 
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
EXPOSE 5000
ARG CLIENT_ID
ARG CLIENT_SECRET
ARG JWT_SECRET_KEY
ARG DATABASE_URL
ARG PORT=5000
ARG REDIRECT_URL=http://127.0.0.1:5000/api/v1/user/oauth
ARG BACKEND_URL=http://localhost:5000
ARG FRONTEND_URL=http://localhost:5173
ARG BUCKET_NAME
ARG AWS_REGION
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ENV CLIENT_ID=$CLIENT_ID
ENV CLIENT_SECRET=$CLIENT_SECRET
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV DATABASE_URL=$DATABASE_URL
ENV PORT=$PORT
ENV REDIRECT_URL=$REDIRECT_URL
ENV BACKEND_URL=$BACKEND_URL
ENV FRONTEND_URL=$FRONTEND_URL
ENV BUCKET_NAME=$BUCKET_NAME
ENV AWS_REGION=$AWS_REGION
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
CMD ["npm","start"]
